### ISSUE TITLE
[Ubuntu 18.04][LXC/LXD] Missing repo key loading dependency "gnupg-agent"

### ISSUE THREAD

**Issue by tomas321** [Provizanta/ansible-role-elasticsearch#1]
lxc container: ubuntu 18.04
missing dependency: gnupg

**Comment by Teebor-Choka** [comment]
Thanks for spotting this one.

Fixed by https://github.com/Provizanta/ansible-role-elasticsearch/commit/dd1d2cb12291edbda4407e76187a62999931df94
